baseURL = "https://kenkoii.github.io"
publishDir = "docs"
languageCode = "en-us"
title = "Jan Kenith Johannessen"

[params]
  name = "Jan Kenith Johannessen"
  description = "Software Developer"
  copyright = "kenkoii"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "https://www.twitter.com/kenkoii"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "https://www.facebook.com/kenkoii"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "https://www.instagram.com/kenkoii"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://www.github.com/kenkoii"

[[params.social]]
  medium = "email"
  icon = "envelope"
  link = "mailto:jankenith.johannessen@gmail.com"